// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: proto/api/pet.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ProtoPetInfo } from "../pet/petinfo.pb.js";
import { ProtoUserSet } from "../user/user_set.pb.js";

export const ProtoPetMessageTypeEnum = {
  UNSPECIFIED: "UNSPECIFIED",
  OFFICIAL: "OFFICIAL",
  CLASSIC: "CLASSIC",
  TEST: "TEST",
  TAIWAN: "TAIWAN",
  CLASSIC_XIN: "CLASSIC_XIN",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type ProtoPetMessageTypeEnum = typeof ProtoPetMessageTypeEnum[keyof typeof ProtoPetMessageTypeEnum];

export namespace ProtoPetMessageTypeEnum {
  export type UNSPECIFIED = typeof ProtoPetMessageTypeEnum.UNSPECIFIED;
  export type OFFICIAL = typeof ProtoPetMessageTypeEnum.OFFICIAL;
  export type CLASSIC = typeof ProtoPetMessageTypeEnum.CLASSIC;
  export type TEST = typeof ProtoPetMessageTypeEnum.TEST;
  export type TAIWAN = typeof ProtoPetMessageTypeEnum.TAIWAN;
  export type CLASSIC_XIN = typeof ProtoPetMessageTypeEnum.CLASSIC_XIN;
  export type UNRECOGNIZED = typeof ProtoPetMessageTypeEnum.UNRECOGNIZED;
}

export function protoPetMessageTypeEnumFromJSON(object: any): ProtoPetMessageTypeEnum {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return ProtoPetMessageTypeEnum.UNSPECIFIED;
    case 1:
    case "OFFICIAL":
      return ProtoPetMessageTypeEnum.OFFICIAL;
    case 2:
    case "CLASSIC":
      return ProtoPetMessageTypeEnum.CLASSIC;
    case 3:
    case "TEST":
      return ProtoPetMessageTypeEnum.TEST;
    case 4:
    case "TAIWAN":
      return ProtoPetMessageTypeEnum.TAIWAN;
    case 10:
    case "CLASSIC_XIN":
      return ProtoPetMessageTypeEnum.CLASSIC_XIN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProtoPetMessageTypeEnum.UNRECOGNIZED;
  }
}

export function protoPetMessageTypeEnumToJSON(object: ProtoPetMessageTypeEnum): string {
  switch (object) {
    case ProtoPetMessageTypeEnum.UNSPECIFIED:
      return "UNSPECIFIED";
    case ProtoPetMessageTypeEnum.OFFICIAL:
      return "OFFICIAL";
    case ProtoPetMessageTypeEnum.CLASSIC:
      return "CLASSIC";
    case ProtoPetMessageTypeEnum.TEST:
      return "TEST";
    case ProtoPetMessageTypeEnum.TAIWAN:
      return "TAIWAN";
    case ProtoPetMessageTypeEnum.CLASSIC_XIN:
      return "CLASSIC_XIN";
    case ProtoPetMessageTypeEnum.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function protoPetMessageTypeEnumToNumber(object: ProtoPetMessageTypeEnum): number {
  switch (object) {
    case ProtoPetMessageTypeEnum.UNSPECIFIED:
      return 0;
    case ProtoPetMessageTypeEnum.OFFICIAL:
      return 1;
    case ProtoPetMessageTypeEnum.CLASSIC:
      return 2;
    case ProtoPetMessageTypeEnum.TEST:
      return 3;
    case ProtoPetMessageTypeEnum.TAIWAN:
      return 4;
    case ProtoPetMessageTypeEnum.CLASSIC_XIN:
      return 10;
    case ProtoPetMessageTypeEnum.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface ProtoPetMessage {
  version: number;
  type: ProtoPetMessageTypeEnum;
  userSet: ProtoUserSet | undefined;
  petInfo: ProtoPetInfo[];
}

function createBaseProtoPetMessage(): ProtoPetMessage {
  return { version: 0, type: ProtoPetMessageTypeEnum.UNSPECIFIED, userSet: undefined, petInfo: [] };
}

export const ProtoPetMessage: MessageFns<ProtoPetMessage> = {
  encode(message: ProtoPetMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== 0) {
      writer.uint32(8).int32(message.version);
    }
    if (message.type !== ProtoPetMessageTypeEnum.UNSPECIFIED) {
      writer.uint32(16).int32(protoPetMessageTypeEnumToNumber(message.type));
    }
    if (message.userSet !== undefined) {
      ProtoUserSet.encode(message.userSet, writer.uint32(26).fork()).join();
    }
    for (const v of message.petInfo) {
      ProtoPetInfo.encode(v!, writer.uint32(74).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtoPetMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProtoPetMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.version = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = protoPetMessageTypeEnumFromJSON(reader.int32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userSet = ProtoUserSet.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.petInfo.push(ProtoPetInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProtoPetMessage {
    return {
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      type: isSet(object.type) ? protoPetMessageTypeEnumFromJSON(object.type) : ProtoPetMessageTypeEnum.UNSPECIFIED,
      userSet: isSet(object.userSet) ? ProtoUserSet.fromJSON(object.userSet) : undefined,
      petInfo: globalThis.Array.isArray(object?.petInfo)
        ? object.petInfo.map((e: any) => ProtoPetInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ProtoPetMessage): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.type !== ProtoPetMessageTypeEnum.UNSPECIFIED) {
      obj.type = protoPetMessageTypeEnumToJSON(message.type);
    }
    if (message.userSet !== undefined) {
      obj.userSet = ProtoUserSet.toJSON(message.userSet);
    }
    if (message.petInfo?.length) {
      obj.petInfo = message.petInfo.map((e) => ProtoPetInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtoPetMessage>, I>>(base?: I): ProtoPetMessage {
    return ProtoPetMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtoPetMessage>, I>>(object: I): ProtoPetMessage {
    const message = createBaseProtoPetMessage();
    message.version = object.version ?? 0;
    message.type = object.type ?? ProtoPetMessageTypeEnum.UNSPECIFIED;
    message.userSet = (object.userSet !== undefined && object.userSet !== null)
      ? ProtoUserSet.fromPartial(object.userSet)
      : undefined;
    message.petInfo = object.petInfo?.map((e) => ProtoPetInfo.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
