// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: proto/pet/ability.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const ProtoPetExtraAbilityType = {
  UNSPECIFIED: "UNSPECIFIED",
  TEAM_TECH: "TEAM_TECH",
  ANNUAL_VIP: "ANNUAL_VIP",
  SUPER_NONO: "SUPER_NONO",
  EXTRA_HP: "EXTRA_HP",
  UNRECOGNIZED: "UNRECOGNIZED",
} as const;

export type ProtoPetExtraAbilityType = typeof ProtoPetExtraAbilityType[keyof typeof ProtoPetExtraAbilityType];

export namespace ProtoPetExtraAbilityType {
  export type UNSPECIFIED = typeof ProtoPetExtraAbilityType.UNSPECIFIED;
  export type TEAM_TECH = typeof ProtoPetExtraAbilityType.TEAM_TECH;
  export type ANNUAL_VIP = typeof ProtoPetExtraAbilityType.ANNUAL_VIP;
  export type SUPER_NONO = typeof ProtoPetExtraAbilityType.SUPER_NONO;
  export type EXTRA_HP = typeof ProtoPetExtraAbilityType.EXTRA_HP;
  export type UNRECOGNIZED = typeof ProtoPetExtraAbilityType.UNRECOGNIZED;
}

export function protoPetExtraAbilityTypeFromJSON(object: any): ProtoPetExtraAbilityType {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return ProtoPetExtraAbilityType.UNSPECIFIED;
    case 1:
    case "TEAM_TECH":
      return ProtoPetExtraAbilityType.TEAM_TECH;
    case 2:
    case "ANNUAL_VIP":
      return ProtoPetExtraAbilityType.ANNUAL_VIP;
    case 3:
    case "SUPER_NONO":
      return ProtoPetExtraAbilityType.SUPER_NONO;
    case 4:
    case "EXTRA_HP":
      return ProtoPetExtraAbilityType.EXTRA_HP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProtoPetExtraAbilityType.UNRECOGNIZED;
  }
}

export function protoPetExtraAbilityTypeToJSON(object: ProtoPetExtraAbilityType): string {
  switch (object) {
    case ProtoPetExtraAbilityType.UNSPECIFIED:
      return "UNSPECIFIED";
    case ProtoPetExtraAbilityType.TEAM_TECH:
      return "TEAM_TECH";
    case ProtoPetExtraAbilityType.ANNUAL_VIP:
      return "ANNUAL_VIP";
    case ProtoPetExtraAbilityType.SUPER_NONO:
      return "SUPER_NONO";
    case ProtoPetExtraAbilityType.EXTRA_HP:
      return "EXTRA_HP";
    case ProtoPetExtraAbilityType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function protoPetExtraAbilityTypeToNumber(object: ProtoPetExtraAbilityType): number {
  switch (object) {
    case ProtoPetExtraAbilityType.UNSPECIFIED:
      return 0;
    case ProtoPetExtraAbilityType.TEAM_TECH:
      return 1;
    case ProtoPetExtraAbilityType.ANNUAL_VIP:
      return 2;
    case ProtoPetExtraAbilityType.SUPER_NONO:
      return 3;
    case ProtoPetExtraAbilityType.EXTRA_HP:
      return 4;
    case ProtoPetExtraAbilityType.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface ProtoPetAbilityValue {
  hp: number;
  atk: number;
  def: number;
  spAtk: number;
  spDef: number;
  spd: number;
}

export interface ProtoPetAbilityValueTotal {
  base: ProtoPetAbilityValue | undefined;
  pvp: ProtoPetAbilityValue | undefined;
  pve: ProtoPetAbilityValue | undefined;
}

export interface ProtoPetExtraAbilityItem {
  type: ProtoPetExtraAbilityType;
  values: ProtoPetAbilityValue | undefined;
}

function createBaseProtoPetAbilityValue(): ProtoPetAbilityValue {
  return { hp: 0, atk: 0, def: 0, spAtk: 0, spDef: 0, spd: 0 };
}

export const ProtoPetAbilityValue: MessageFns<ProtoPetAbilityValue> = {
  encode(message: ProtoPetAbilityValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hp !== 0) {
      writer.uint32(8).int32(message.hp);
    }
    if (message.atk !== 0) {
      writer.uint32(16).int32(message.atk);
    }
    if (message.def !== 0) {
      writer.uint32(24).int32(message.def);
    }
    if (message.spAtk !== 0) {
      writer.uint32(32).int32(message.spAtk);
    }
    if (message.spDef !== 0) {
      writer.uint32(40).int32(message.spDef);
    }
    if (message.spd !== 0) {
      writer.uint32(48).int32(message.spd);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtoPetAbilityValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProtoPetAbilityValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hp = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.atk = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.def = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.spAtk = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.spDef = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.spd = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProtoPetAbilityValue {
    return {
      hp: isSet(object.hp) ? globalThis.Number(object.hp) : 0,
      atk: isSet(object.atk) ? globalThis.Number(object.atk) : 0,
      def: isSet(object.def) ? globalThis.Number(object.def) : 0,
      spAtk: isSet(object.spAtk) ? globalThis.Number(object.spAtk) : 0,
      spDef: isSet(object.spDef) ? globalThis.Number(object.spDef) : 0,
      spd: isSet(object.spd) ? globalThis.Number(object.spd) : 0,
    };
  },

  toJSON(message: ProtoPetAbilityValue): unknown {
    const obj: any = {};
    if (message.hp !== 0) {
      obj.hp = Math.round(message.hp);
    }
    if (message.atk !== 0) {
      obj.atk = Math.round(message.atk);
    }
    if (message.def !== 0) {
      obj.def = Math.round(message.def);
    }
    if (message.spAtk !== 0) {
      obj.spAtk = Math.round(message.spAtk);
    }
    if (message.spDef !== 0) {
      obj.spDef = Math.round(message.spDef);
    }
    if (message.spd !== 0) {
      obj.spd = Math.round(message.spd);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtoPetAbilityValue>, I>>(base?: I): ProtoPetAbilityValue {
    return ProtoPetAbilityValue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtoPetAbilityValue>, I>>(object: I): ProtoPetAbilityValue {
    const message = createBaseProtoPetAbilityValue();
    message.hp = object.hp ?? 0;
    message.atk = object.atk ?? 0;
    message.def = object.def ?? 0;
    message.spAtk = object.spAtk ?? 0;
    message.spDef = object.spDef ?? 0;
    message.spd = object.spd ?? 0;
    return message;
  },
};

function createBaseProtoPetAbilityValueTotal(): ProtoPetAbilityValueTotal {
  return { base: undefined, pvp: undefined, pve: undefined };
}

export const ProtoPetAbilityValueTotal: MessageFns<ProtoPetAbilityValueTotal> = {
  encode(message: ProtoPetAbilityValueTotal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.base !== undefined) {
      ProtoPetAbilityValue.encode(message.base, writer.uint32(10).fork()).join();
    }
    if (message.pvp !== undefined) {
      ProtoPetAbilityValue.encode(message.pvp, writer.uint32(18).fork()).join();
    }
    if (message.pve !== undefined) {
      ProtoPetAbilityValue.encode(message.pve, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtoPetAbilityValueTotal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProtoPetAbilityValueTotal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.base = ProtoPetAbilityValue.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pvp = ProtoPetAbilityValue.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pve = ProtoPetAbilityValue.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProtoPetAbilityValueTotal {
    return {
      base: isSet(object.base) ? ProtoPetAbilityValue.fromJSON(object.base) : undefined,
      pvp: isSet(object.pvp) ? ProtoPetAbilityValue.fromJSON(object.pvp) : undefined,
      pve: isSet(object.pve) ? ProtoPetAbilityValue.fromJSON(object.pve) : undefined,
    };
  },

  toJSON(message: ProtoPetAbilityValueTotal): unknown {
    const obj: any = {};
    if (message.base !== undefined) {
      obj.base = ProtoPetAbilityValue.toJSON(message.base);
    }
    if (message.pvp !== undefined) {
      obj.pvp = ProtoPetAbilityValue.toJSON(message.pvp);
    }
    if (message.pve !== undefined) {
      obj.pve = ProtoPetAbilityValue.toJSON(message.pve);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtoPetAbilityValueTotal>, I>>(base?: I): ProtoPetAbilityValueTotal {
    return ProtoPetAbilityValueTotal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtoPetAbilityValueTotal>, I>>(object: I): ProtoPetAbilityValueTotal {
    const message = createBaseProtoPetAbilityValueTotal();
    message.base = (object.base !== undefined && object.base !== null)
      ? ProtoPetAbilityValue.fromPartial(object.base)
      : undefined;
    message.pvp = (object.pvp !== undefined && object.pvp !== null)
      ? ProtoPetAbilityValue.fromPartial(object.pvp)
      : undefined;
    message.pve = (object.pve !== undefined && object.pve !== null)
      ? ProtoPetAbilityValue.fromPartial(object.pve)
      : undefined;
    return message;
  },
};

function createBaseProtoPetExtraAbilityItem(): ProtoPetExtraAbilityItem {
  return { type: ProtoPetExtraAbilityType.UNSPECIFIED, values: undefined };
}

export const ProtoPetExtraAbilityItem: MessageFns<ProtoPetExtraAbilityItem> = {
  encode(message: ProtoPetExtraAbilityItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== ProtoPetExtraAbilityType.UNSPECIFIED) {
      writer.uint32(8).int32(protoPetExtraAbilityTypeToNumber(message.type));
    }
    if (message.values !== undefined) {
      ProtoPetAbilityValue.encode(message.values, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtoPetExtraAbilityItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProtoPetExtraAbilityItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = protoPetExtraAbilityTypeFromJSON(reader.int32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.values = ProtoPetAbilityValue.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProtoPetExtraAbilityItem {
    return {
      type: isSet(object.type) ? protoPetExtraAbilityTypeFromJSON(object.type) : ProtoPetExtraAbilityType.UNSPECIFIED,
      values: isSet(object.values) ? ProtoPetAbilityValue.fromJSON(object.values) : undefined,
    };
  },

  toJSON(message: ProtoPetExtraAbilityItem): unknown {
    const obj: any = {};
    if (message.type !== ProtoPetExtraAbilityType.UNSPECIFIED) {
      obj.type = protoPetExtraAbilityTypeToJSON(message.type);
    }
    if (message.values !== undefined) {
      obj.values = ProtoPetAbilityValue.toJSON(message.values);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtoPetExtraAbilityItem>, I>>(base?: I): ProtoPetExtraAbilityItem {
    return ProtoPetExtraAbilityItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtoPetExtraAbilityItem>, I>>(object: I): ProtoPetExtraAbilityItem {
    const message = createBaseProtoPetExtraAbilityItem();
    message.type = object.type ?? ProtoPetExtraAbilityType.UNSPECIFIED;
    message.values = (object.values !== undefined && object.values !== null)
      ? ProtoPetAbilityValue.fromPartial(object.values)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
