// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: proto/pet/mintmark.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PetAbilityValue } from "./ability.pb.js";

export enum MintmarkType {
  UNSPECIFIED = "UNSPECIFIED",
  SKILL = "SKILL",
  ABILITY = "ABILITY",
  UNIVERSAL = "UNIVERSAL",
  QUANXIAO = "QUANXIAO",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function mintmarkTypeFromJSON(object: any): MintmarkType {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return MintmarkType.UNSPECIFIED;
    case 1:
    case "SKILL":
      return MintmarkType.SKILL;
    case 2:
    case "ABILITY":
      return MintmarkType.ABILITY;
    case 3:
    case "UNIVERSAL":
      return MintmarkType.UNIVERSAL;
    case 4:
    case "QUANXIAO":
      return MintmarkType.QUANXIAO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MintmarkType.UNRECOGNIZED;
  }
}

export function mintmarkTypeToJSON(object: MintmarkType): string {
  switch (object) {
    case MintmarkType.UNSPECIFIED:
      return "UNSPECIFIED";
    case MintmarkType.SKILL:
      return "SKILL";
    case MintmarkType.ABILITY:
      return "ABILITY";
    case MintmarkType.UNIVERSAL:
      return "UNIVERSAL";
    case MintmarkType.QUANXIAO:
      return "QUANXIAO";
    case MintmarkType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export function mintmarkTypeToNumber(object: MintmarkType): number {
  switch (object) {
    case MintmarkType.UNSPECIFIED:
      return 0;
    case MintmarkType.SKILL:
      return 1;
    case MintmarkType.ABILITY:
      return 2;
    case MintmarkType.UNIVERSAL:
      return 3;
    case MintmarkType.QUANXIAO:
      return 4;
    case MintmarkType.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface GemItem {
  category: number;
  level: number;
}

export interface SkillMintmarkInfo {
  type: MintmarkType;
  id: number;
  skillID: number;
}

export interface AbilityMintmarkInfo {
  type: MintmarkType;
  id: number;
  AbilityValues: PetAbilityValue | undefined;
}

export interface UniversalMintmarkInfo {
  type: MintmarkType;
  id: number;
  AbilityValues: PetAbilityValue | undefined;
  classID: number;
  gem: GemItem | undefined;
}

export interface QuanxiaoMintmarkInfo {
  type: MintmarkType;
  id: number;
  AbilityValues: PetAbilityValue | undefined;
  skillID: number;
}

export interface MintmarkInfo {
  mintmark?:
    | //
    { $case: "skill"; value: SkillMintmarkInfo }
    | //
    { $case: "ability"; value: AbilityMintmarkInfo }
    | //
    { $case: "universal"; value: UniversalMintmarkInfo }
    | //
    { $case: "quanxiao"; value: QuanxiaoMintmarkInfo }
    | undefined;
}

function createBaseGemItem(): GemItem {
  return { category: 0, level: 0 };
}

export const GemItem: MessageFns<GemItem> = {
  encode(message: GemItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.category !== 0) {
      writer.uint32(8).int32(message.category);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GemItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGemItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.category = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GemItem {
    return {
      category: isSet(object.category) ? globalThis.Number(object.category) : 0,
      level: isSet(object.level) ? globalThis.Number(object.level) : 0,
    };
  },

  toJSON(message: GemItem): unknown {
    const obj: any = {};
    if (message.category !== 0) {
      obj.category = Math.round(message.category);
    }
    if (message.level !== 0) {
      obj.level = Math.round(message.level);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GemItem>, I>>(base?: I): GemItem {
    return GemItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GemItem>, I>>(object: I): GemItem {
    const message = createBaseGemItem();
    message.category = object.category ?? 0;
    message.level = object.level ?? 0;
    return message;
  },
};

function createBaseSkillMintmarkInfo(): SkillMintmarkInfo {
  return { type: MintmarkType.UNSPECIFIED, id: 0, skillID: 0 };
}

export const SkillMintmarkInfo: MessageFns<SkillMintmarkInfo> = {
  encode(message: SkillMintmarkInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== MintmarkType.UNSPECIFIED) {
      writer.uint32(8).int32(mintmarkTypeToNumber(message.type));
    }
    if (message.id !== 0) {
      writer.uint32(16).int32(message.id);
    }
    if (message.skillID !== 0) {
      writer.uint32(24).int32(message.skillID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SkillMintmarkInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSkillMintmarkInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = mintmarkTypeFromJSON(reader.int32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.skillID = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SkillMintmarkInfo {
    return {
      type: isSet(object.type) ? mintmarkTypeFromJSON(object.type) : MintmarkType.UNSPECIFIED,
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      skillID: isSet(object.skillID) ? globalThis.Number(object.skillID) : 0,
    };
  },

  toJSON(message: SkillMintmarkInfo): unknown {
    const obj: any = {};
    if (message.type !== MintmarkType.UNSPECIFIED) {
      obj.type = mintmarkTypeToJSON(message.type);
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.skillID !== 0) {
      obj.skillID = Math.round(message.skillID);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SkillMintmarkInfo>, I>>(base?: I): SkillMintmarkInfo {
    return SkillMintmarkInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SkillMintmarkInfo>, I>>(object: I): SkillMintmarkInfo {
    const message = createBaseSkillMintmarkInfo();
    message.type = object.type ?? MintmarkType.UNSPECIFIED;
    message.id = object.id ?? 0;
    message.skillID = object.skillID ?? 0;
    return message;
  },
};

function createBaseAbilityMintmarkInfo(): AbilityMintmarkInfo {
  return { type: MintmarkType.UNSPECIFIED, id: 0, AbilityValues: undefined };
}

export const AbilityMintmarkInfo: MessageFns<AbilityMintmarkInfo> = {
  encode(message: AbilityMintmarkInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== MintmarkType.UNSPECIFIED) {
      writer.uint32(8).int32(mintmarkTypeToNumber(message.type));
    }
    if (message.id !== 0) {
      writer.uint32(16).int32(message.id);
    }
    if (message.AbilityValues !== undefined) {
      PetAbilityValue.encode(message.AbilityValues, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AbilityMintmarkInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAbilityMintmarkInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = mintmarkTypeFromJSON(reader.int32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.AbilityValues = PetAbilityValue.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AbilityMintmarkInfo {
    return {
      type: isSet(object.type) ? mintmarkTypeFromJSON(object.type) : MintmarkType.UNSPECIFIED,
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      AbilityValues: isSet(object.AbilityValues) ? PetAbilityValue.fromJSON(object.AbilityValues) : undefined,
    };
  },

  toJSON(message: AbilityMintmarkInfo): unknown {
    const obj: any = {};
    if (message.type !== MintmarkType.UNSPECIFIED) {
      obj.type = mintmarkTypeToJSON(message.type);
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.AbilityValues !== undefined) {
      obj.AbilityValues = PetAbilityValue.toJSON(message.AbilityValues);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AbilityMintmarkInfo>, I>>(base?: I): AbilityMintmarkInfo {
    return AbilityMintmarkInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AbilityMintmarkInfo>, I>>(object: I): AbilityMintmarkInfo {
    const message = createBaseAbilityMintmarkInfo();
    message.type = object.type ?? MintmarkType.UNSPECIFIED;
    message.id = object.id ?? 0;
    message.AbilityValues = (object.AbilityValues !== undefined && object.AbilityValues !== null)
      ? PetAbilityValue.fromPartial(object.AbilityValues)
      : undefined;
    return message;
  },
};

function createBaseUniversalMintmarkInfo(): UniversalMintmarkInfo {
  return { type: MintmarkType.UNSPECIFIED, id: 0, AbilityValues: undefined, classID: 0, gem: undefined };
}

export const UniversalMintmarkInfo: MessageFns<UniversalMintmarkInfo> = {
  encode(message: UniversalMintmarkInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== MintmarkType.UNSPECIFIED) {
      writer.uint32(8).int32(mintmarkTypeToNumber(message.type));
    }
    if (message.id !== 0) {
      writer.uint32(16).int32(message.id);
    }
    if (message.AbilityValues !== undefined) {
      PetAbilityValue.encode(message.AbilityValues, writer.uint32(26).fork()).join();
    }
    if (message.classID !== 0) {
      writer.uint32(32).int32(message.classID);
    }
    if (message.gem !== undefined) {
      GemItem.encode(message.gem, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UniversalMintmarkInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUniversalMintmarkInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = mintmarkTypeFromJSON(reader.int32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.AbilityValues = PetAbilityValue.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.classID = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.gem = GemItem.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UniversalMintmarkInfo {
    return {
      type: isSet(object.type) ? mintmarkTypeFromJSON(object.type) : MintmarkType.UNSPECIFIED,
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      AbilityValues: isSet(object.AbilityValues) ? PetAbilityValue.fromJSON(object.AbilityValues) : undefined,
      classID: isSet(object.classID) ? globalThis.Number(object.classID) : 0,
      gem: isSet(object.gem) ? GemItem.fromJSON(object.gem) : undefined,
    };
  },

  toJSON(message: UniversalMintmarkInfo): unknown {
    const obj: any = {};
    if (message.type !== MintmarkType.UNSPECIFIED) {
      obj.type = mintmarkTypeToJSON(message.type);
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.AbilityValues !== undefined) {
      obj.AbilityValues = PetAbilityValue.toJSON(message.AbilityValues);
    }
    if (message.classID !== 0) {
      obj.classID = Math.round(message.classID);
    }
    if (message.gem !== undefined) {
      obj.gem = GemItem.toJSON(message.gem);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UniversalMintmarkInfo>, I>>(base?: I): UniversalMintmarkInfo {
    return UniversalMintmarkInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UniversalMintmarkInfo>, I>>(object: I): UniversalMintmarkInfo {
    const message = createBaseUniversalMintmarkInfo();
    message.type = object.type ?? MintmarkType.UNSPECIFIED;
    message.id = object.id ?? 0;
    message.AbilityValues = (object.AbilityValues !== undefined && object.AbilityValues !== null)
      ? PetAbilityValue.fromPartial(object.AbilityValues)
      : undefined;
    message.classID = object.classID ?? 0;
    message.gem = (object.gem !== undefined && object.gem !== null) ? GemItem.fromPartial(object.gem) : undefined;
    return message;
  },
};

function createBaseQuanxiaoMintmarkInfo(): QuanxiaoMintmarkInfo {
  return { type: MintmarkType.UNSPECIFIED, id: 0, AbilityValues: undefined, skillID: 0 };
}

export const QuanxiaoMintmarkInfo: MessageFns<QuanxiaoMintmarkInfo> = {
  encode(message: QuanxiaoMintmarkInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== MintmarkType.UNSPECIFIED) {
      writer.uint32(8).int32(mintmarkTypeToNumber(message.type));
    }
    if (message.id !== 0) {
      writer.uint32(16).int32(message.id);
    }
    if (message.AbilityValues !== undefined) {
      PetAbilityValue.encode(message.AbilityValues, writer.uint32(26).fork()).join();
    }
    if (message.skillID !== 0) {
      writer.uint32(32).int32(message.skillID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuanxiaoMintmarkInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuanxiaoMintmarkInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = mintmarkTypeFromJSON(reader.int32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.AbilityValues = PetAbilityValue.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.skillID = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuanxiaoMintmarkInfo {
    return {
      type: isSet(object.type) ? mintmarkTypeFromJSON(object.type) : MintmarkType.UNSPECIFIED,
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      AbilityValues: isSet(object.AbilityValues) ? PetAbilityValue.fromJSON(object.AbilityValues) : undefined,
      skillID: isSet(object.skillID) ? globalThis.Number(object.skillID) : 0,
    };
  },

  toJSON(message: QuanxiaoMintmarkInfo): unknown {
    const obj: any = {};
    if (message.type !== MintmarkType.UNSPECIFIED) {
      obj.type = mintmarkTypeToJSON(message.type);
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.AbilityValues !== undefined) {
      obj.AbilityValues = PetAbilityValue.toJSON(message.AbilityValues);
    }
    if (message.skillID !== 0) {
      obj.skillID = Math.round(message.skillID);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuanxiaoMintmarkInfo>, I>>(base?: I): QuanxiaoMintmarkInfo {
    return QuanxiaoMintmarkInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuanxiaoMintmarkInfo>, I>>(object: I): QuanxiaoMintmarkInfo {
    const message = createBaseQuanxiaoMintmarkInfo();
    message.type = object.type ?? MintmarkType.UNSPECIFIED;
    message.id = object.id ?? 0;
    message.AbilityValues = (object.AbilityValues !== undefined && object.AbilityValues !== null)
      ? PetAbilityValue.fromPartial(object.AbilityValues)
      : undefined;
    message.skillID = object.skillID ?? 0;
    return message;
  },
};

function createBaseMintmarkInfo(): MintmarkInfo {
  return { mintmark: undefined };
}

export const MintmarkInfo: MessageFns<MintmarkInfo> = {
  encode(message: MintmarkInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.mintmark?.$case) {
      case "skill":
        SkillMintmarkInfo.encode(message.mintmark.value, writer.uint32(10).fork()).join();
        break;
      case "ability":
        AbilityMintmarkInfo.encode(message.mintmark.value, writer.uint32(18).fork()).join();
        break;
      case "universal":
        UniversalMintmarkInfo.encode(message.mintmark.value, writer.uint32(26).fork()).join();
        break;
      case "quanxiao":
        QuanxiaoMintmarkInfo.encode(message.mintmark.value, writer.uint32(34).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MintmarkInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMintmarkInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mintmark = { $case: "skill", value: SkillMintmarkInfo.decode(reader, reader.uint32()) };
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.mintmark = { $case: "ability", value: AbilityMintmarkInfo.decode(reader, reader.uint32()) };
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mintmark = { $case: "universal", value: UniversalMintmarkInfo.decode(reader, reader.uint32()) };
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.mintmark = { $case: "quanxiao", value: QuanxiaoMintmarkInfo.decode(reader, reader.uint32()) };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MintmarkInfo {
    return {
      mintmark: isSet(object.skill)
        ? { $case: "skill", value: SkillMintmarkInfo.fromJSON(object.skill) }
        : isSet(object.ability)
        ? { $case: "ability", value: AbilityMintmarkInfo.fromJSON(object.ability) }
        : isSet(object.universal)
        ? { $case: "universal", value: UniversalMintmarkInfo.fromJSON(object.universal) }
        : isSet(object.quanxiao)
        ? { $case: "quanxiao", value: QuanxiaoMintmarkInfo.fromJSON(object.quanxiao) }
        : undefined,
    };
  },

  toJSON(message: MintmarkInfo): unknown {
    const obj: any = {};
    if (message.mintmark?.$case === "skill") {
      obj.skill = SkillMintmarkInfo.toJSON(message.mintmark.value);
    }
    if (message.mintmark?.$case === "ability") {
      obj.ability = AbilityMintmarkInfo.toJSON(message.mintmark.value);
    }
    if (message.mintmark?.$case === "universal") {
      obj.universal = UniversalMintmarkInfo.toJSON(message.mintmark.value);
    }
    if (message.mintmark?.$case === "quanxiao") {
      obj.quanxiao = QuanxiaoMintmarkInfo.toJSON(message.mintmark.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MintmarkInfo>, I>>(base?: I): MintmarkInfo {
    return MintmarkInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MintmarkInfo>, I>>(object: I): MintmarkInfo {
    const message = createBaseMintmarkInfo();
    if (object.mintmark?.$case === "skill" && object.mintmark?.value !== undefined && object.mintmark?.value !== null) {
      message.mintmark = { $case: "skill", value: SkillMintmarkInfo.fromPartial(object.mintmark.value) };
    }
    if (
      object.mintmark?.$case === "ability" && object.mintmark?.value !== undefined && object.mintmark?.value !== null
    ) {
      message.mintmark = { $case: "ability", value: AbilityMintmarkInfo.fromPartial(object.mintmark.value) };
    }
    if (
      object.mintmark?.$case === "universal" && object.mintmark?.value !== undefined && object.mintmark?.value !== null
    ) {
      message.mintmark = { $case: "universal", value: UniversalMintmarkInfo.fromPartial(object.mintmark.value) };
    }
    if (
      object.mintmark?.$case === "quanxiao" && object.mintmark?.value !== undefined && object.mintmark?.value !== null
    ) {
      message.mintmark = { $case: "quanxiao", value: QuanxiaoMintmarkInfo.fromPartial(object.mintmark.value) };
    }
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
